
## Con Docker: http://localhost:8080
## Con .NET Debug: https://localhost:7089
@BaseAddress = http://localhost:8080

###

GET {{BaseAddress}}/v1/products/11111111-1111-1111-1111-111111111111
Accept: application/json

###

POST {{BaseAddress}}/v1/products
Accept: application/json
Content-Type: application/json

{
   "nombre": "Producto 1",
   "descripcion": "Descripción del producto 1",
   "precio": 100.00
}
