
## Con Docker: http://localhost:8080
## Con .NET Debug (Profile https): https://localhost:7089
@BaseAddress = http://localhost:8080

### Obtener un producto por ID

GET {{BaseAddress}}/v1/products/11111111-1111-1111-1111-111111111111
Accept: application/json

### Listar productos (skip y take son obligatorios; búsqueda opcional)

GET {{BaseAddress}}/v1/products?skip=0&take=10&search=producto
Accept: application/json


### Ajustar el stock (cantidad positiva suma, negativa resta)

PATCH {{BaseAddress}}/v1/products/actualizar-stock
Accept: application/json
Content-Type: application/json

{
   "id": "11111111-1111-1111-1111-111111111111",
   "cantidad": 2
}

### Intentar crear producto (Error de validación)

POST {{BaseAddress}}/v1/products
Accept: application/json
Content-Type: application/json

{
   "nombre": "XX",
   "descripcion": "XX",
   "precio": 0,
   "stockInicial": 10
}

### Crear un producto correctamente

POST {{BaseAddress}}/v1/products
Accept: application/json
Content-Type: application/json

{
   "nombre": "Monitor Samsung 24",
   "descripcion": "Monitor de 24 pulgadas, Full HD y tecnología LED.",
   "precio": 50000,
   "stockInicial": 10
}

### Confirmar que el producto fue creado correctamente

GET {{BaseAddress}}/v1/products/c3617987-8984-40af-9ec5-cf11982d97f7
Accept: application/json
